//! v0.33.2 — `mnemonic import-wallet` Electrum BIE1 (user-password) whole-file
//! storage decryption integration cells.
//!
//! Fixtures (`tests/fixtures/wallet_import/electrum-bie1-storage-bip84.txt`,
//! `electrum-bie2-storage.txt`) are generated by the INDEPENDENT pure-Python
//! `ecdsa` regen script `tests/external/regen_electrum_bie1_storage.py`
//! (faithful to spesmilo/electrum @ 2e640c83) — a cross-impl witness of the
//! whole-file `zlib(json)` → ECIES framing. The crypto itself is separately
//! validated byte-exact against Electrum's OWN committed KATs in
//! `src/electrum_crypto.rs`. The BIE1 fixture decrypts (password `satoshi`)
//! to the existing `electrum-standard-bip84-mainnet.json` wallet.

use assert_cmd::Command;
use std::path::PathBuf;

const PASSWORD: &str = "satoshi";

fn fixture_path(name: &str) -> PathBuf {
    PathBuf::from("tests/fixtures/wallet_import").join(name)
}

fn import_cmd() -> Command {
    let mut cmd = Command::cargo_bin("mnemonic").unwrap();
    cmd.arg("import-wallet");
    cmd
}

// ── happy paths ───────────────────────────────────────────────────────────

#[test]
fn bie1_storage_inline_password_decrypts_and_imports() {
    let p = fixture_path("electrum-bie1-storage-bip84.txt");
    let out = import_cmd()
        .args(["--blob", p.to_str().unwrap(), "--decrypt-password", PASSWORD])
        .assert()
        .success();
    let o = out.get_output();
    let stdout = String::from_utf8(o.stdout.clone()).unwrap();
    let stderr = String::from_utf8(o.stderr.clone()).unwrap();
    assert!(stdout.contains("cosigners=1"), "stdout: {stdout}");
    assert!(stdout.contains("network=mainnet"), "stdout: {stdout}");
    assert!(
        stderr.contains("BIE1 user-password storage decrypted"),
        "expected decrypt notice; stderr: {stderr}"
    );
    // inline password → argv-leakage advisory.
    assert!(
        stderr.contains("secret material on argv"),
        "expected argv advisory; stderr: {stderr}"
    );
}

#[test]
fn bie1_storage_password_file_decrypts_and_imports() {
    let p = fixture_path("electrum-bie1-storage-bip84.txt");
    let pwfile = tempfile::NamedTempFile::new().unwrap();
    std::fs::write(pwfile.path(), PASSWORD).unwrap();
    let out = import_cmd()
        .args([
            "--blob",
            p.to_str().unwrap(),
            "--decrypt-password-file",
            pwfile.path().to_str().unwrap(),
        ])
        .assert()
        .success();
    let stdout = String::from_utf8(out.get_output().stdout.clone()).unwrap();
    assert!(stdout.contains("cosigners=1"), "stdout: {stdout}");
    assert!(stdout.contains("network=mainnet"), "stdout: {stdout}");
}

#[test]
fn bie1_storage_password_stdin_decrypts_and_imports() {
    let p = fixture_path("electrum-bie1-storage-bip84.txt");
    let out = import_cmd()
        .args([
            "--blob",
            p.to_str().unwrap(),
            "--decrypt-password-stdin",
        ])
        .write_stdin(PASSWORD)
        .assert()
        .success();
    let stdout = String::from_utf8(out.get_output().stdout.clone()).unwrap();
    assert!(stdout.contains("cosigners=1"), "stdout: {stdout}");
}

// ── negatives ───────────────────────────────────────────────────────────────

#[test]
fn bie1_storage_wrong_password_unified_failure() {
    let p = fixture_path("electrum-bie1-storage-bip84.txt");
    let out = import_cmd()
        .args([
            "--blob",
            p.to_str().unwrap(),
            "--decrypt-password",
            "wrong-password",
        ])
        .assert()
        .failure();
    let stderr = String::from_utf8(out.get_output().stderr.clone()).unwrap();
    assert!(
        stderr.contains("decryption failed (wrong password or corrupted wallet file)"),
        "expected unified non-leaky failure; stderr: {stderr}"
    );
}

#[test]
fn bie2_storage_hardware_device_refused() {
    let p = fixture_path("electrum-bie2-storage.txt");
    let out = import_cmd()
        .args([
            "--blob",
            p.to_str().unwrap(),
            "--decrypt-password",
            PASSWORD,
        ])
        .assert()
        .failure();
    let stderr = String::from_utf8(out.get_output().stderr.clone()).unwrap();
    assert!(
        stderr.contains("hardware-device key (BIE2 / XPUB_PASSWORD)"),
        "expected BIE2 refusal; stderr: {stderr}"
    );
}

#[test]
fn bie1_storage_without_password_demands_one() {
    let p = fixture_path("electrum-bie1-storage-bip84.txt");
    let out = import_cmd()
        .args(["--blob", p.to_str().unwrap()])
        .assert()
        .failure();
    let stderr = String::from_utf8(out.get_output().stderr.clone()).unwrap();
    assert!(
        stderr.contains("BIE1 storage-encrypted wallet detected")
            && stderr.contains("--decrypt-password"),
        "expected demand-password error; stderr: {stderr}"
    );
}

#[test]
fn bie1_blob_stdin_plus_password_stdin_refused() {
    // --blob=- and --decrypt-password-stdin both consume stdin.
    let out = import_cmd()
        .args(["--blob", "-", "--decrypt-password-stdin"])
        .write_stdin("ignored")
        .assert()
        .failure();
    let stderr = String::from_utf8(out.get_output().stderr.clone()).unwrap();
    assert!(
        stderr.contains("--blob=- and --decrypt-password-stdin cannot both read from stdin"),
        "expected stdin-contention refusal; stderr: {stderr}"
    );
}

#[test]
fn bsms_token_stdin_plus_password_stdin_refused() {
    // --bsms-encryption-token=- and --decrypt-password-stdin both consume stdin.
    let out = import_cmd()
        .args([
            "--blob",
            fixture_path("electrum-bie1-storage-bip84.txt").to_str().unwrap(),
            "--bsms-encryption-token",
            "-",
            "--decrypt-password-stdin",
        ])
        .write_stdin("ignored")
        .assert()
        .failure();
    let stderr = String::from_utf8(out.get_output().stderr.clone()).unwrap();
    assert!(
        stderr.contains(
            "--bsms-encryption-token=- and --decrypt-password-stdin cannot both read from stdin"
        ),
        "expected stdin-contention refusal; stderr: {stderr}"
    );
}

#[test]
fn format_bsms_with_bie1_decrypts_then_mismatches_electrum() {
    // Detection is --format-independent: the BIE1 blob decrypts (notice), then
    // the recovered JSON sniffs as electrum and the --format bsms arm refuses.
    let p = fixture_path("electrum-bie1-storage-bip84.txt");
    let out = import_cmd()
        .args([
            "--blob",
            p.to_str().unwrap(),
            "--format",
            "bsms",
            "--decrypt-password",
            PASSWORD,
        ])
        .assert()
        .failure();
    let o = out.get_output();
    let stderr = String::from_utf8(o.stderr.clone()).unwrap();
    assert!(
        stderr.contains("BIE1 user-password storage decrypted"),
        "expected decrypt notice before mismatch; stderr: {stderr}"
    );
    assert!(
        stderr.contains("bsms") && stderr.contains("electrum"),
        "expected format-mismatch bsms/electrum; stderr: {stderr}"
    );
}

#[test]
fn password_supplied_for_plaintext_wallet_is_ignored() {
    // A plaintext (non-BIE1) Electrum wallet + a password → soft notice, normal import.
    let p = fixture_path("electrum-standard-bip84-mainnet.json");
    let out = import_cmd()
        .args([
            "--blob",
            p.to_str().unwrap(),
            "--decrypt-password",
            PASSWORD,
        ])
        .assert()
        .success();
    let o = out.get_output();
    let stdout = String::from_utf8(o.stdout.clone()).unwrap();
    let stderr = String::from_utf8(o.stderr.clone()).unwrap();
    assert!(stdout.contains("cosigners=1"), "stdout: {stdout}");
    assert!(
        stderr.contains("no BIE1 storage-encrypted wallet detected")
            && stderr.contains("ignored"),
        "expected soft ignored notice; stderr: {stderr}"
    );
    // The inline password still leaked via argv even though it was unused.
    assert!(
        stderr.contains("secret material on argv"),
        "expected argv advisory even when password ignored; stderr: {stderr}"
    );
}
