//! P2.3 (pathless/dead-card partial-decode) — `mnemonic inspect --md1`
//! inherits the md-codec partial-allowing decode.
//!
//! Per `design/IMPLEMENTATION_PLAN_pathless_partial_decode.md` §P2.3 +
//! `design/SPEC_pathless_partial_decode.md`. A `canonical_origin == None` md1
//! card with no explicit per-`@N` origin (a "dead card") now PARTIAL-decodes on
//! `mnemonic inspect`:
//!   - the `template:` line still renders (origin-independent);
//!   - an explicit `origin: «unspecified — supply on restore»` marker is added
//!     (NO fake `m/...` path);
//!   - a stderr note fires; exit **4** (VERIFY-ME);
//!   - `--json` gains an additive `partial` object; `schema_version` unchanged.
//!   - Canonical shapes stay exit 0, byte-identical (BOUNDARY RED-proof).
//!
//! I-2: the toolkit `mnemonic inspect --md1` decode is CHUNK-FORM only, so ALL
//! fixtures here are built as chunk-of-N via `md_codec::chunk::split` (mirroring
//! `tests/cli_inspect.rs::rechunk`). A plain single-string md1 still hits the
//! pre-existing `unsupported version 2` intake gap (out of scope; FOLLOWUP
//! `toolkit-inspect-nonchunked-md1-intake-gap`).

#![allow(missing_docs)]

use assert_cmd::Command;
use md_codec::DecodeOpts;

/// Verbatim marker (byte-identical to md-cli's `ORIGIN_UNSPECIFIED_MARKER`).
const ORIGIN_MARKER: &str = "origin: \u{ab}unspecified \u{2014} supply on restore\u{bb}";

/// Frozen single-string dead md1 cards (`canonical_origin == None`, no origin).
/// Generated by `md encode --group-size 0 <template>` (md-cli 0.13.0).
const DEAD_SINGLES: &[(&str, &str)] = &[
    (
        "sh_sortedmulti",
        "md1yppqqxp3cg2x3r70ckk4kjaf",
        // template rendered by descriptor_to_template
    ),
    ("tr_taptree", "md1yppqqxqj2s4dk6hk0wrt5n3"),
];

const DEAD_TEMPLATES: &[(&str, &str)] = &[
    ("sh_sortedmulti", "sh(sortedmulti(2,@0/<0;1>/*,@1/<0;1>/*))"),
    ("tr_taptree", "tr(@0/<0;1>/*,pk(@1/<0;1>/*))"),
];

/// A canonical (fully-specified) shape — BOUNDARY control. `wpkh(@0/<0;1>/*)`.
const CANONICAL_SINGLE: &str = "md1yqpqqxqq8xtwhw4xwn4qh";
const CANONICAL_TEMPLATE: &str = "wpkh(@0/<0;1>/*)";

/// A KEYED, MULTI-CHUNK (4-chunk) `tr(sortedmulti_a(2,…))` card WITH origin
/// `m/87'/0'/0'` (from `mnemonic bundle --template tr-sortedmulti-a`). Eliding
/// its origin yields a KEYED multi-chunk DEAD card — the substrate for the
/// content-id-oracle RED-proof (the doctoring needs 2+ chunks to mix set-ids).
const KEYED_ORIGIN_MD1: &[&str] = &[
    "md1fypsppspqfm67zzqqvpeyy9p0p9cdzxlr9pj9qps4cyst7a0v9dqxjg406uy6llxvywv2quayl75ggm8hqt",
    "md1fypsppsvlcu6jsa6jdz69hy75rzqkjnyqzvheytfy9mjcppayp9n2lz42cd7ju7kdqa6uzgezf9vwalc8nl",
    "md1fypspps3j7vgkacswhccv5tpx2s4feevxsd3mta6k0mpf2dw678vsdfa3pu0hswnvwhxsktnd8g86jpq9km",
    "md1fypsppsu5lw2qhcnezhhjv6cjmcqmu328ay376tgu7u2ty8elftecmq3qe7afhljyr8edgcxt4mqkq",
];

/// Elide the origin of a keyed card → a KEYED dead card (chunk-form). The tree
/// is `canonical_origin == None` (taproot-multisig) so the elided origin has no
/// canonical default → `unresolved_origin_indices()` non-empty.
fn elide_keyed(md1: &[&str]) -> md_codec::Descriptor {
    use md_codec::origin_path::{OriginPath, PathDeclPaths};
    let mut d = md_codec::chunk::reassemble(md1).expect("decode keyed card WITH origin");
    d.path_decl.paths = PathDeclPaths::Shared(OriginPath { components: vec![] });
    d
}

fn keyed_dead_chunks() -> Vec<String> {
    md_codec::chunk::split(&elide_keyed(KEYED_ORIGIN_MD1)).expect("split keyed dead card")
}

/// Decode a frozen single-string dead card under PARTIAL opts and re-split into
/// the chunk-form the toolkit's `mnemonic inspect --md1` can decode.
fn dead_chunks(single: &str) -> Vec<String> {
    let d = md_codec::decode_md1_string_with_opts(single, DecodeOpts::partial())
        .expect("partial-decode frozen dead single-string");
    md_codec::chunk::split(&d).expect("split dead descriptor into chunk-form")
}

/// Decode a canonical single-string (strict) and re-split into chunk-form.
fn canonical_chunks(single: &str) -> Vec<String> {
    let d = md_codec::decode_md1_string(single).expect("strict-decode canonical single-string");
    md_codec::chunk::split(&d).expect("split canonical descriptor into chunk-form")
}

fn inspect_args(chunks: &[String], json: bool) -> Vec<String> {
    let mut args = vec!["inspect".to_string()];
    if json {
        args.push("--json".to_string());
    }
    for c in chunks {
        args.push("--md1".to_string());
        args.push(c.clone());
    }
    args
}

// ─── partial: text ────────────────────────────────────────────────────────

#[test]
fn inspect_md1_dead_card_text_renders_marker_and_exits_4() {
    for ((name, single), (_, template)) in DEAD_SINGLES.iter().zip(DEAD_TEMPLATES) {
        let chunks = dead_chunks(single);
        let out = Command::cargo_bin("mnemonic")
            .unwrap()
            .args(inspect_args(&chunks, false))
            .output()
            .unwrap();
        assert_eq!(
            out.status.code(),
            Some(4),
            "[{name}] dead card must partial-decode with exit 4; stderr={:?}",
            String::from_utf8_lossy(&out.stderr)
        );
        let stdout = String::from_utf8(out.stdout).unwrap();
        assert!(
            stdout.contains(&format!("template: {template}")),
            "[{name}] template line missing; got {stdout:?}"
        );
        assert!(
            stdout.contains(ORIGIN_MARKER),
            "[{name}] origin-unspecified marker missing; got {stdout:?}"
        );
        // Never print a fake `m/` path on a dead card.
        assert!(
            !stdout.contains("origin_path: m/"),
            "[{name}] must NOT print a fake m/ path; got {stdout:?}"
        );
        let stderr = String::from_utf8(out.stderr).unwrap();
        assert!(
            stderr.contains("VERIFY-ME"),
            "[{name}] expected a partial-decode stderr note; got {stderr:?}"
        );
    }
}

// ─── partial: json ────────────────────────────────────────────────────────

#[test]
fn inspect_md1_dead_card_json_has_partial_field_and_schema_unchanged() {
    for (name, single) in DEAD_SINGLES {
        let chunks = dead_chunks(single);
        let out = Command::cargo_bin("mnemonic")
            .unwrap()
            .args(inspect_args(&chunks, true))
            .output()
            .unwrap();
        assert_eq!(out.status.code(), Some(4), "[{name}] json partial exit 4");
        let stdout = String::from_utf8(out.stdout).unwrap();
        let v: serde_json::Value = serde_json::from_str(&stdout).unwrap();
        assert_eq!(
            v["schema_version"], "2",
            "[{name}] schema_version must stay \"2\" (additive partial field); got {v}"
        );
        assert_eq!(
            v["partial"]["reason"], "missing_explicit_origin",
            "[{name}] partial.reason mismatch; got {v}"
        );
        assert!(
            !v["partial"]["unresolved_indices"]
                .as_array()
                .unwrap_or_else(|| panic!("[{name}] unresolved_indices array; got {v}"))
                .is_empty(),
            "[{name}] unresolved_indices non-empty; got {v}"
        );
        // template still present.
        assert!(v["template"].is_string(), "[{name}] template present; got {v}");
    }
}

// ─── BOUNDARY (RED-proof): canonical stays exit 0, no marker, no partial ────

#[test]
fn inspect_md1_canonical_card_stays_exit_0_no_marker() {
    let chunks = canonical_chunks(CANONICAL_SINGLE);
    let out = Command::cargo_bin("mnemonic")
        .unwrap()
        .args(inspect_args(&chunks, false))
        .output()
        .unwrap();
    assert_eq!(out.status.code(), Some(0), "canonical card must stay exit 0");
    let stdout = String::from_utf8(out.stdout).unwrap();
    assert!(
        stdout.contains(&format!("template: {CANONICAL_TEMPLATE}")),
        "canonical template line missing; got {stdout:?}"
    );
    assert!(
        !stdout.contains(ORIGIN_MARKER),
        "canonical card must NEVER show the origin-unspecified marker; got {stdout:?}"
    );
}

#[test]
fn inspect_md1_canonical_card_json_no_partial_key_schema_2() {
    let chunks = canonical_chunks(CANONICAL_SINGLE);
    let out = Command::cargo_bin("mnemonic")
        .unwrap()
        .args(inspect_args(&chunks, true))
        .output()
        .unwrap();
    assert_eq!(out.status.code(), Some(0), "canonical must stay exit 0");
    let stdout = String::from_utf8(out.stdout).unwrap();
    let v: serde_json::Value = serde_json::from_str(&stdout).unwrap();
    assert_eq!(v["schema_version"], "2");
    assert!(
        v.get("partial").is_none(),
        "canonical card JSON must NOT carry a `partial` key; got {v}"
    );
}

// ─── M-3b: auto-repair does NOT fire on an intact dead card ─────────────────

#[test]
fn inspect_md1_dead_card_auto_repair_clean_fallthrough() {
    // WITHOUT --no-auto-repair: an intact dead card is an Ok-partial (not a
    // decode-error), so the `is_codec_decode_err` auto-fire trigger must NOT
    // fire → exit 4 (partial), never exit 5 (repair short-circuit).
    let chunks = dead_chunks(DEAD_SINGLES[0].1);
    let out = Command::cargo_bin("mnemonic")
        .unwrap()
        .args(inspect_args(&chunks, false))
        // deliberately force TTY so auto-repair gating would otherwise engage.
        .env("MNEMONIC_FORCE_TTY", "1")
        .output()
        .unwrap();
    assert_eq!(
        out.status.code(),
        Some(4),
        "intact dead card must partial-decode (exit 4), not auto-repair short-circuit (exit 5); \
         stderr={:?}",
        String::from_utf8_lossy(&out.stderr)
    );
}

// ─── funds-critical: doctored content-id chunked dead card REJECTS ──────────

#[test]
fn inspect_md1_multi_chunk_keyed_dead_card_partial_renders_exit_4() {
    // Sanity substrate: the KEYED multi-chunk dead card partial-renders (exit 4)
    // so the doctored negative below is a meaningful contrast.
    let chunks = keyed_dead_chunks();
    assert!(chunks.len() >= 2, "fixture must be multi-chunk; got {chunks:?}");
    let out = Command::cargo_bin("mnemonic")
        .unwrap()
        .args(inspect_args(&chunks, false))
        .arg("--no-auto-repair")
        .output()
        .unwrap();
    assert_eq!(out.status.code(), Some(4), "keyed multi-chunk dead card → exit 4");
    let stdout = String::from_utf8(out.stdout).unwrap();
    assert!(stdout.contains(ORIGIN_MARKER), "marker missing; got {stdout:?}");
}

#[test]
fn inspect_md1_doctored_content_id_dead_card_does_not_partial_render() {
    // Build a clean KEYED multi-chunk dead card, then swap in a FOREIGN chunk
    // (from a descriptor with a mutated pubkey → different content-id). The
    // cross-chunk content-id oracle stays enforced under partial → this must
    // NOT partial-render (exit != 4) and must NOT emit the origin marker.
    let mut foreign_d = elide_keyed(KEYED_ORIGIN_MD1);
    if let Some(pks) = foreign_d.tlv.pubkeys.as_mut() {
        pks[0].1[10] ^= 0x01; // shift content-id
    }
    let clean = keyed_dead_chunks();
    let foreign = md_codec::chunk::split(&foreign_d).expect("split foreign");
    assert!(clean.len() >= 2 && foreign.len() >= 2, "need multi-chunk to mix set-ids");
    // clean chunks + one foreign chunk substituted at index 1.
    let mut doctored = clean.clone();
    doctored[1] = foreign[1].clone();

    let out = Command::cargo_bin("mnemonic")
        .unwrap()
        .args(inspect_args(&doctored, false))
        .arg("--no-auto-repair")
        .output()
        .unwrap();
    assert_ne!(
        out.status.code(),
        Some(4),
        "doctored-content-id chunked dead card must NOT partial-render (oracle intact); stderr={:?}",
        String::from_utf8_lossy(&out.stderr)
    );
    let stdout = String::from_utf8(out.stdout).unwrap();
    assert!(
        !stdout.contains(ORIGIN_MARKER),
        "doctored card must NOT show the origin-unspecified marker; got {stdout:?}"
    );
}

// ─── cross-binary parity (M-3a) — MD_BIN-gated ─────────────────────────────

fn md_bin() -> Option<String> {
    std::env::var("MD_BIN").ok()
}

#[test]
#[ignore = "needs MD_BIN=/path/to/md (cross-binary parity; no in-workspace md)"]
fn inspect_md1_cross_binary_template_parity_with_md_decode() {
    let md = match md_bin() {
        Some(p) => p,
        None => {
            eprintln!("SKIP: MD_BIN unset");
            return;
        }
    };
    for ((name, single), (_, template)) in DEAD_SINGLES.iter().zip(DEAD_TEMPLATES) {
        let chunks = dead_chunks(single);
        // md decode <chunks...> — chunk-form multi-arg.
        let md_out = std::process::Command::new(&md)
            .arg("decode")
            .args(&chunks)
            .output()
            .unwrap();
        assert_eq!(
            md_out.status.code(),
            Some(4),
            "[{name}] md decode dead card must exit 4"
        );
        let md_stdout = String::from_utf8(md_out.stdout).unwrap();
        // md decode leads with the raw template line.
        let md_template = md_stdout.lines().next().unwrap_or("");
        assert_eq!(md_template, *template, "[{name}] md decode template line");

        let mn_out = Command::cargo_bin("mnemonic")
            .unwrap()
            .args(inspect_args(&chunks, false))
            .output()
            .unwrap();
        assert_eq!(mn_out.status.code(), Some(4), "[{name}] mnemonic inspect exit 4");
        let mn_stdout = String::from_utf8(mn_out.stdout).unwrap();
        let mn_template = mn_stdout
            .lines()
            .find_map(|l| l.strip_prefix("template: "))
            .unwrap_or("");
        assert_eq!(
            mn_template, md_template,
            "[{name}] cross-binary template must be byte-identical"
        );
    }
}
