#!/usr/bin/env bash
# tests/verify-examples-gui.sh
#
# Output-fidelity gate for the GENERATED GUI FORM RENDERS (the `.gui`
# structural renders embedded in the manual via `include="gui/<stem>.gui"`).
#
# This is the form-render analogue of tests/verify-examples.sh (which gates
# the worked-example CLI `.out` transcripts). It is a SEPARATE script — the
# `verify-examples.sh` in this dir is a SYMLINK to ../../manual/tests/, shared
# across books, and must NOT be edited.
#
# What it does:
#   1. Regenerates the full `<tab>-<sub>.gui` set into a fresh temp dir by
#      running the PINNED `gui-render --emit-all` (the same headless,
#      egui-free `--no-default-features` binary the manual is pinned to).
#   2. CENSUS: asserts the regenerated set has exactly $EXPECTED_COUNT files
#      (one per subcommand in the pinned GUI schema, incl. zero-identity
#      subs) AND that the committed set has the same count — fail-closed.
#   3. DIFF: byte-diffs the regenerated set against the committed
#      transcripts/gui/ tree. ANY drift (changed content, extra file, or
#      missing file) fails the gate, exactly like verify-examples does for
#      `.out` goldens.
#   4. SECRET HYGIENE: defensively asserts no render leaks a cleartext
#      secret — every flag/positional row marked `(... secret ...)` must
#      carry the `<masked>` sentinel (or be the always-disabled secret
#      `*-stdin` checkbox). The renderer masks by construction; this is a
#      belt-and-braces check on the committed + regenerated bytes.
#
# Args (NAME=value):
#   GUI_RENDER_BIN   — invocation string for the pinned gui-render binary.
#                      Either an absolute path, or a `cargo run … --` prefix
#                      (the Makefile default builds it from the pinned
#                      mnemonic-gui checkout under --no-default-features).
#                      `--emit-all <dir>` is appended by this script.
#   TRANSCRIPTS_GUI  — absolute path to the committed transcripts/gui/ dir.
#   EXPECTED_COUNT   — the pinned GUI schema's subcommand total (census key).
#
# Called from the Makefile as `make verify-examples-gui`.

set -euo pipefail

EXPECTED_COUNT=""
for arg in "$@"; do
  case "$arg" in
    GUI_RENDER_BIN=*)  GUI_RENDER_BIN="${arg#*=}" ;;
    TRANSCRIPTS_GUI=*) TRANSCRIPTS_GUI="${arg#*=}" ;;
    EXPECTED_COUNT=*)  EXPECTED_COUNT="${arg#*=}" ;;
  esac
done

: "${GUI_RENDER_BIN:?GUI_RENDER_BIN is required (path to, or cargo-run invocation of, the pinned gui-render)}"
: "${TRANSCRIPTS_GUI:?TRANSCRIPTS_GUI is required (committed transcripts/gui dir)}"
: "${EXPECTED_COUNT:?EXPECTED_COUNT is required (pinned GUI schema subcommand total)}"

if [ ! -d "$TRANSCRIPTS_GUI" ]; then
  echo "[verify-examples-gui] FAIL: committed render dir missing: $TRANSCRIPTS_GUI" >&2
  exit 1
fi

regen="$(mktemp -d)"
trap 'rm -rf "$regen"' EXIT

# Regenerate the full render set. GUI_RENDER_BIN may be a multi-word
# `cargo run … --` invocation, so it is intentionally unquoted here.
echo "[verify-examples-gui] regenerating renders with: $GUI_RENDER_BIN --emit-all $regen"
# shellcheck disable=SC2086
$GUI_RENDER_BIN --emit-all "$regen"

# --- CENSUS -----------------------------------------------------------------
regen_count=$(find "$regen" -maxdepth 1 -type f -name '*.gui' | wc -l | tr -d ' ')
committed_count=$(find "$TRANSCRIPTS_GUI" -maxdepth 1 -type f -name '*.gui' | wc -l | tr -d ' ')

fail=0
if [ "$regen_count" -ne "$EXPECTED_COUNT" ]; then
  echo "[verify-examples-gui] FAIL: census — pinned gui-render emitted $regen_count renders, expected $EXPECTED_COUNT" >&2
  fail=1
fi
if [ "$committed_count" -ne "$EXPECTED_COUNT" ]; then
  echo "[verify-examples-gui] FAIL: census — committed transcripts/gui has $committed_count renders, expected $EXPECTED_COUNT" >&2
  fail=1
fi

# --- DIFF (fail-closed on ANY drift, incl. extra/missing files) -------------
if ! diff -r "$TRANSCRIPTS_GUI" "$regen" >/tmp/_gui_diff 2>&1; then
  echo "[verify-examples-gui] FAIL: regenerated renders drifted from committed transcripts/gui:" >&2
  sed 's/^/    /' /tmp/_gui_diff >&2 || true
  fail=1
fi
rm -f /tmp/_gui_diff

# --- SECRET HYGIENE ---------------------------------------------------------
# A row flagged `(... secret ...)` must show the <masked> sentinel, OR be the
# always-disabled secret `*-stdin` checkbox ([disabled]). Anything else means
# a render leaked a cleartext secret value.
leak=$(grep -rnE '\(([a-z]+, )*secret([, ][a-z]+)*\)' "$TRANSCRIPTS_GUI" "$regen" \
         | grep -vE '<masked>|\[disabled\]' || true)
if [ -n "$leak" ]; then
  echo "[verify-examples-gui] FAIL: secret-marked render row without <masked>/[disabled] (possible cleartext secret leak):" >&2
  echo "$leak" | sed 's/^/    /' >&2
  fail=1
fi

if [ "$fail" -ne 0 ]; then
  echo "[verify-examples-gui] FAILED" >&2
  exit 1
fi
echo "[verify-examples-gui] OK ($committed_count/$EXPECTED_COUNT renders match the pinned gui-render; no secret leak)"
