//! `volvelle-verify` — emit canonical (input, codec_output) vectors for the
//! m-format constellation BCH paper-computer wheels.
//!
//! Behavioral drift-gate (no codec internals serialized). The Python helper
//! at `docs/tools/make-volvelle-data.py` consumes the emitted TOML, runs the
//! BIP-93 polymod transcription against each `input` string, and asserts
//! the BCH residue matches the format's NUMS-derived target constant.
//! Helper-vs-codec divergence (or helper-vs-BIP-93 transcription error)
//! halts the volvelle build.
//!
//! `codec_output` is emitted byte-identical to `input`: this binary's role
//! is to confirm the codec accepts the canonical strings (decode succeeds)
//! and to anchor the canonical-vector list as a Rust-checked source of
//! truth. Round-trip-via-encode would regenerate chunk_set_id and is
//! orthogonal to the BCH math the wheel implements.

use mk_codec::KeyCard;
use md_codec::Descriptor;

/// Canonical mk1-long fixture: line 7 of
/// `docs/manual/transcripts/22-first-bundle.out` — the first chunk of the
/// worked-example mk1 chunk-set (BIP 48 multisig, mainnet). Length 111
/// puts it in the long-code BCH(108,93,8) range.
const MK1_LONG: &str =
    "mk1qprsqhpqqsq3cqtsleeutks2qvzg3vs70mejhk622ws2kgdemj2cd8zwj2skzx2wq0qw70l4q99vdyh5x0z8v4yslsp8qp3yxg3dpe854wq4";

/// Canonical mk1-regular fixture: line 8 of the same transcript — the
/// second chunk of the same chunk-set. Length 80 is regular-code
/// BCH(93,80,8).
const MK1_REGULAR: &str =
    "mk1qprsqhpp0f30mtxzd65mvwcur9usdatwuqvq6z70r9nwrgk6xn6l8gy6nwa2n977sw6zh34rma0nh";

/// Canonical md1-regular fixture: the `pkh_basic` test vector from md-codec
/// `tests/vectors/pkh_basic.phrase.txt`. Pinned to the on-disk md-codec
/// version so decode succeeds without wire-format-version skew (the
/// toolkit `transcripts/22-first-bundle.out` md1 strings predate this
/// crate's md-codec version).
const MD1_REGULAR: &str = "md1qqpqqxyepwspuepy268e";

fn main() {
    // Sanity: decode each canonical string through the codec's public API
    // to confirm the strings parse cleanly. Decode is the integration
    // touch-point that proves the codec accepts these vectors.
    let mk1_chunks = [MK1_LONG, MK1_REGULAR];
    let _mk1_card: KeyCard =
        mk_codec::decode(&mk1_chunks).expect("mk1 chunk-set decode (canonical fixture)");
    let _md1_card: Descriptor =
        md_codec::decode_md1_string(MD1_REGULAR).expect("md1 decode (canonical fixture)");

    println!("# Generated by `cargo run --bin print-constants` (run from docs/volvelles/verify/). Do not hand-edit.");
    println!();
    println!("schema_version = 1");
    println!();

    emit_vector("mk1-regular", MK1_REGULAR);
    emit_vector("mk1-long", MK1_LONG);
    emit_vector("md1-regular", MD1_REGULAR);
}

fn emit_vector(format: &str, canonical: &str) {
    println!("[[canonical_vectors]]");
    println!("format       = \"{format}\"");
    println!("input        = \"{canonical}\"");
    println!("codec_output = \"{canonical}\"");
    println!();
}
