//! BIP-129 Round-1 5-line key record parser (Signer → Coordinator).
//!
//! Per BIP-129 §Specification → §Setup Process → ====Round 1==== =====Signer=====
//! (verbatim quote in `design/agent-reports/v0_27_0-phase-2-bip129-recon.md`):
//!
//! > *"The first line in the record must be the specification version
//! > (`BSMS 1.0` as of this writing). The second line must be the hex-encoded
//! > `TOKEN`. The third line must be the `KEY`. The `KEY` is a public key or
//! > an XPUB plus the key origin information, written in the descriptor-defined
//! > format, i.e.: `[{master key fingerprint}/{derivation path}]{KEY}`. The
//! > fourth line is a text description of the key, 80 characters maximum. The
//! > fifth line must be a `SIG`, whereas `SIG` is the signature generated by
//! > using the private key associated with the public key or XPUB to sign the
//! > first four lines. The signature should follow BIP-0322, legacy format
//! > accepted."*
//!
//! This module parses a Round-1 record into a typed `BsmsRound1Record` and
//! exposes `signer_pubkey` to extract the signing pubkey for verification.
//! Signature verification lives in the sibling `bsms_verify` module.

use crate::error::ToolkitError;
use bitcoin::bip32::{DerivationPath, Fingerprint, Xpub};
use bitcoin::secp256k1::PublicKey;
use std::str::FromStr;

pub(crate) const BSMS_HEADER: &str = "BSMS 1.0";

/// Maximum description length per BIP-129 line 81: "80 characters maximum".
pub(crate) const MAX_DESCRIPTION_LEN: usize = 80;

/// Parsed BIP-129 Round-1 5-line key record (Signer → Coordinator).
#[derive(Debug, Clone)]
pub(crate) struct BsmsRound1Record {
    /// Line 1 — must equal `BSMS 1.0`.
    #[allow(dead_code)]
    pub(crate) version: String,
    /// Line 2 — hex-encoded TOKEN. BIP-129 §Encryption modes:
    /// `"00"` (NO_ENCRYPTION, 1 byte 0x00 as 2 hex chars),
    /// 16 hex chars (STANDARD, 64-bit nonce),
    /// 32 hex chars (EXTENDED, 128-bit nonce).
    pub(crate) token_hex: String,
    /// Line 3 — parsed `[fingerprint/path]KEY`. KEY is either a raw 33-byte
    /// compressed pubkey or a BIP-32 xpub.
    pub(crate) key_field: KeyField,
    /// Line 4 — text description, <= 80 chars, no `\n` / `\r`.
    pub(crate) description: String,
    /// Line 5 — base64-encoded 65-byte BIP-322 legacy-format recoverable
    /// ECDSA signature.
    pub(crate) signature_b64: String,
}

#[derive(Debug, Clone)]
pub(crate) enum KeyField {
    /// Raw compressed public key (NO_ENCRYPTION/pubkey mode, e.g. BIP-129 TV-1).
    RawPubkey {
        #[allow(dead_code)]
        fingerprint: Fingerprint,
        #[allow(dead_code)]
        path: DerivationPath,
        pubkey: PublicKey,
    },
    /// BIP-32 extended public key (NO_ENCRYPTION/xpub or any encrypted mode,
    /// e.g. BIP-129 TV-2 through TV-4).
    Xpub {
        #[allow(dead_code)]
        fingerprint: Fingerprint,
        #[allow(dead_code)]
        path: DerivationPath,
        xpub: Xpub,
    },
}

/// Parse a BIP-129 Round-1 record from its UTF-8 text form.
///
/// Performs CRLF→LF normalize, then asserts:
/// - 5 lines (allowing one trailing empty element from trailing `\n`).
/// - Line 1 == `BSMS 1.0`.
/// - Line 3 parses as `[<8-hex>/<path>]<key>` where key is either 66-hex pubkey
///   or base58 xpub.
/// - Line 4 is <= 80 chars and contains no `\n` / `\r` / `\0` bytes after
///   normalize.
/// - Line 5 is non-empty (full base64 decode validation happens in
///   `bsms_verify::verify_round1_signature`).
pub(crate) fn parse_round1(text: &str) -> Result<BsmsRound1Record, ToolkitError> {
    let normalized = text.replace("\r\n", "\n");
    let mut lines: Vec<&str> = normalized.split('\n').collect();

    // Strip one trailing empty element (caused by trailing newline).
    if lines.last().map(|s| s.is_empty()).unwrap_or(false) {
        lines.pop();
    }

    if lines.len() != 5 {
        return Err(ToolkitError::BsmsRound1Malformed {
            reason: format!(
                "expected 5 lines (version / hex-TOKEN / KEY / description / SIG), got {}",
                lines.len()
            ),
        });
    }

    if lines[0] != BSMS_HEADER {
        return Err(ToolkitError::BsmsRound1Malformed {
            reason: format!(
                "expected line 1 == {:?} (BIP-129 §Round 1 Signer), got {:?}",
                BSMS_HEADER, lines[0]
            ),
        });
    }

    let token_hex = lines[1].to_string();
    if !is_valid_token_hex(&token_hex) {
        return Err(ToolkitError::BsmsRound1Malformed {
            reason: format!(
                "line 2 TOKEN: expected hex (\"00\" for NO_ENCRYPTION, 16 chars STANDARD, \
                 32 chars EXTENDED), got {:?}",
                token_hex
            ),
        });
    }

    let key_field = parse_key_field(lines[2])?;

    let description = lines[3].to_string();
    if description.contains('\r') {
        return Err(ToolkitError::BsmsRound1Malformed {
            reason: "line 4 description contains carriage return (\\r); BIP-129 §Round 1 \
                     description is one line, max 80 chars"
                .to_string(),
        });
    }
    if description.chars().count() > MAX_DESCRIPTION_LEN {
        return Err(ToolkitError::BsmsRound1Malformed {
            reason: format!(
                "line 4 description {} chars; BIP-129 §Round 1 mandates max {}",
                description.chars().count(),
                MAX_DESCRIPTION_LEN
            ),
        });
    }

    let signature_b64 = lines[4].to_string();
    if signature_b64.is_empty() {
        return Err(ToolkitError::BsmsRound1Malformed {
            reason: "line 5 SIG is empty; BIP-129 §Round 1 requires a base64 SIG".to_string(),
        });
    }

    Ok(BsmsRound1Record {
        version: lines[0].to_string(),
        token_hex,
        key_field,
        description,
        signature_b64,
    })
}

/// Extract the signing pubkey from the parsed Round-1 record per BIP-129
/// line 81: *"the private key associated with the public key or XPUB"*.
/// - `KeyField::RawPubkey` → the embedded pubkey directly.
/// - `KeyField::Xpub` → the xpub's OWN embedded pubkey (bytes 45-78 of the
///   serialized xpub), NOT any child-derived key. Consensus reading via
///   Coinkite Python reference impl.
pub(crate) fn signer_pubkey(record: &BsmsRound1Record) -> PublicKey {
    match &record.key_field {
        KeyField::RawPubkey { pubkey, .. } => *pubkey,
        KeyField::Xpub { xpub, .. } => xpub.public_key,
    }
}

/// Reconstruct the 4-line signed body (lines 1-4 of the Round-1 record),
/// joined by `\n` with NO trailing newline, per BIP-129 line 81 *"sign the
/// first four lines"* + Coinkite ref impl's `"\n".join(...)` convention.
pub(crate) fn signed_body(record: &BsmsRound1Record) -> String {
    let key_line = key_field_to_line(&record.key_field);
    format!(
        "{}\n{}\n{}\n{}",
        record.version, record.token_hex, key_line, record.description
    )
}

/// Re-serialize a `KeyField` back to its `[fp/path]KEY` line-3 wire shape.
/// Used to construct the BIP-322 signed body verbatim.
fn key_field_to_line(field: &KeyField) -> String {
    match field {
        KeyField::RawPubkey {
            fingerprint,
            path,
            pubkey,
        } => format!(
            "[{}/{}]{}",
            fingerprint,
            format_path_no_m_prefix(path),
            hex::encode(pubkey.serialize())
        ),
        KeyField::Xpub {
            fingerprint,
            path,
            xpub,
        } => format!(
            "[{}/{}]{}",
            fingerprint,
            format_path_no_m_prefix(path),
            xpub
        ),
    }
}

fn format_path_no_m_prefix(path: &DerivationPath) -> String {
    // bitcoin::bip32::DerivationPath::Display emits "m/84'/0'/0'"; BIP-129
    // line-3 KEY uses "[fp/84'/0'/0']xpub..." (no leading "m/"). Strip it.
    let full = path.to_string();
    full.strip_prefix("m/").unwrap_or(&full).to_string()
}

fn is_valid_token_hex(s: &str) -> bool {
    matches!(s.len(), 2 | 16 | 32) && s.chars().all(|c| c.is_ascii_hexdigit())
}

fn parse_key_field(line: &str) -> Result<KeyField, ToolkitError> {
    // Shape: `[<fingerprint>/<derivation-path>]<key>`
    let body = line
        .strip_prefix('[')
        .ok_or_else(|| ToolkitError::BsmsRound1Malformed {
            reason: format!(
                "line 3 KEY: expected `[<fp>/<path>]<key>` shape, got {:?}",
                line
            ),
        })?;
    let close = body
        .find(']')
        .ok_or_else(|| ToolkitError::BsmsRound1Malformed {
            reason: format!(
                "line 3 KEY: missing closing `]` for key-origin `[fp/path]` prefix in {:?}",
                line
            ),
        })?;
    let origin = &body[..close];
    let key_str = &body[close + 1..];

    let (fp_str, path_str) =
        origin
            .split_once('/')
            .ok_or_else(|| ToolkitError::BsmsRound1Malformed {
                reason: format!(
                    "line 3 KEY: key origin {:?} missing `/` separator between fingerprint and \
                     derivation path",
                    origin
                ),
            })?;

    let fingerprint =
        Fingerprint::from_str(fp_str).map_err(|e| ToolkitError::BsmsRound1Malformed {
            reason: format!("line 3 KEY: malformed fingerprint {:?}: {}", fp_str, e),
        })?;

    let derivation_path = if path_str.is_empty() {
        DerivationPath::master()
    } else {
        // BIP-129 line 3 paths are non-`m`-prefixed (e.g. `48'/0'/0'/2'`).
        // bitcoin::bip32::DerivationPath::from_str accepts both with and
        // without the `m/` prefix; we accept both to be permissive.
        let with_m = if path_str.starts_with("m/") || path_str == "m" {
            path_str.to_string()
        } else {
            format!("m/{}", path_str)
        };
        DerivationPath::from_str(&with_m).map_err(|e| ToolkitError::BsmsRound1Malformed {
            reason: format!(
                "line 3 KEY: malformed derivation path {:?}: {}",
                path_str, e
            ),
        })?
    };

    if key_str.is_empty() {
        return Err(ToolkitError::BsmsRound1Malformed {
            reason: format!(
                "line 3 KEY: empty key body after `[fp/path]` prefix in {:?}",
                line
            ),
        });
    }

    // Dispatch on key shape: 33-byte hex pubkey (66 ASCII chars) vs base58 xpub.
    let key_field = if key_str.len() == 66 && key_str.chars().all(|c| c.is_ascii_hexdigit()) {
        let bytes = hex::decode(key_str).map_err(|e| ToolkitError::BsmsRound1Malformed {
            reason: format!("line 3 KEY: malformed pubkey hex: {}", e),
        })?;
        let pubkey =
            PublicKey::from_slice(&bytes).map_err(|e| ToolkitError::BsmsRound1Malformed {
                reason: format!("line 3 KEY: invalid secp256k1 pubkey: {}", e),
            })?;
        KeyField::RawPubkey {
            fingerprint,
            path: derivation_path,
            pubkey,
        }
    } else {
        let xpub = Xpub::from_str(key_str).map_err(|e| ToolkitError::BsmsRound1Malformed {
            reason: format!(
                "line 3 KEY: not a 66-hex compressed pubkey, and xpub parse failed: {}",
                e
            ),
        })?;
        KeyField::Xpub {
            fingerprint,
            path: derivation_path,
            xpub,
        }
    };

    Ok(key_field)
}

#[cfg(test)]
mod tests {
    //! Unit cells for the Round-1 parser. Format-level coverage only;
    //! signature-verify cells live in `bsms_verify::tests` + the integration
    //! tests in `tests/cli_bsms_round1.rs` against BIP-129 published TVs.

    use super::*;

    const TV1_RECORD: &str = "BSMS 1.0\n00\n[59865f44/48'/0'/0'/2']026d15412460ba0d881c21837bb999233896085a9ed4e5445bd637c10e579768ba\nSigner 1 key\nH6DXgqkCb353BDPkzppMFpOcdJZlpur0WRetQhIBqSn6DFzoQWBtm+ibP5wERDRNi0bxxev9B+FIvyQWq0s6im4=\n";

    const TV2_RECORD: &str = "BSMS 1.0\n00\n[1cf0bf7e/48'/0'/0'/2']xpub6FL8FhxNNUVnG64YurPd16AfGyvFLhh7S2uSsDqR3Qfcm6o9jtcMYwh6DvmcBF9qozxNQmTCVvWtxLpKTnhVLN3Pgnu2D3pAoXYFgVyd8Yz\nSigner 1 key\nIB7v+qi1b+Xrwm/3bF+Rjl8QbIJ/FMQ40kUsOOQo1SqUWn5QlFWbBD8BKPRetfo1L1N7DmYjVscZNsmMrqRJGWw=\n";

    #[test]
    fn parse_tv1_raw_pubkey_record_round_trips() {
        let r = parse_round1(TV1_RECORD).expect("TV-1 parse");
        assert_eq!(r.version, "BSMS 1.0");
        assert_eq!(r.token_hex, "00");
        assert_eq!(r.description, "Signer 1 key");
        assert!(matches!(r.key_field, KeyField::RawPubkey { .. }));
        // Signed body bytes verbatim.
        let body = signed_body(&r);
        assert_eq!(
            body,
            "BSMS 1.0\n00\n[59865f44/48'/0'/0'/2']\
             026d15412460ba0d881c21837bb999233896085a9ed4e5445bd637c10e579768ba\nSigner 1 key"
        );
    }

    #[test]
    fn parse_tv2_xpub_record_round_trips() {
        let r = parse_round1(TV2_RECORD).expect("TV-2 parse");
        assert_eq!(r.token_hex, "00");
        assert!(matches!(r.key_field, KeyField::Xpub { .. }));
        let body = signed_body(&r);
        assert!(body.starts_with("BSMS 1.0\n00\n[1cf0bf7e/48'/0'/0'/2']xpub6FL8F"));
        assert!(body.ends_with("Signer 1 key"));
        assert!(
            !body.ends_with('\n'),
            "signed body must not have trailing newline"
        );
    }

    #[test]
    fn parse_crlf_normalized() {
        let crlf = TV1_RECORD.replace('\n', "\r\n");
        let r = parse_round1(&crlf).expect("CRLF parse");
        assert_eq!(r.version, "BSMS 1.0");
    }

    #[test]
    fn parse_rejects_wrong_line_count() {
        let four_lines = "BSMS 1.0\n00\n[59865f44/48'/0'/0'/2']026d15412460ba0d881c21837bb999233896085a9ed4e5445bd637c10e579768ba\nSigner 1 key\n";
        assert!(matches!(
            parse_round1(four_lines),
            Err(ToolkitError::BsmsRound1Malformed { .. })
        ));
    }

    #[test]
    fn parse_rejects_wrong_header() {
        let bad = TV1_RECORD.replacen("BSMS 1.0", "BSMS 2.0", 1);
        assert!(matches!(
            parse_round1(&bad),
            Err(ToolkitError::BsmsRound1Malformed { .. })
        ));
    }

    #[test]
    fn parse_rejects_malformed_token_hex() {
        let bad = TV1_RECORD.replacen("\n00\n", "\n0\n", 1); // odd-length hex
        assert!(matches!(
            parse_round1(&bad),
            Err(ToolkitError::BsmsRound1Malformed { .. })
        ));
    }

    #[test]
    fn parse_rejects_oversized_description() {
        let long = "x".repeat(MAX_DESCRIPTION_LEN + 1);
        let bad = TV1_RECORD.replacen("Signer 1 key", &long, 1);
        assert!(matches!(
            parse_round1(&bad),
            Err(ToolkitError::BsmsRound1Malformed { .. })
        ));
    }

    /// v0.27.0 Phase 6.5 PR-review S3 fold — boundary test: exactly
    /// `MAX_DESCRIPTION_LEN` (80) chars MUST parse; one more (81) MUST
    /// reject. Pinning both sides locks the off-by-one risk.
    #[test]
    fn parse_description_at_boundary_80_accepts_81_rejects() {
        let at_limit = "x".repeat(MAX_DESCRIPTION_LEN);
        let one_over = "x".repeat(MAX_DESCRIPTION_LEN + 1);

        let ok = TV1_RECORD.replacen("Signer 1 key", &at_limit, 1);
        let r = parse_round1(&ok).expect("80-char description must parse");
        assert_eq!(r.description.chars().count(), MAX_DESCRIPTION_LEN);

        let bad = TV1_RECORD.replacen("Signer 1 key", &one_over, 1);
        assert!(matches!(
            parse_round1(&bad),
            Err(ToolkitError::BsmsRound1Malformed { .. })
        ));
    }

    #[test]
    fn signer_pubkey_for_raw_pubkey_returns_embedded_pubkey() {
        let r = parse_round1(TV1_RECORD).expect("TV-1");
        let pk = signer_pubkey(&r);
        let expected_bytes =
            hex::decode("026d15412460ba0d881c21837bb999233896085a9ed4e5445bd637c10e579768ba")
                .unwrap();
        assert_eq!(pk.serialize().to_vec(), expected_bytes);
    }

    #[test]
    fn signer_pubkey_for_xpub_returns_xpubs_own_embedded_pubkey() {
        let r = parse_round1(TV2_RECORD).expect("TV-2");
        let pk = signer_pubkey(&r);
        // The xpub TV-2 starts with xpub6FL8F... — its embedded pubkey is the
        // 33-byte compressed key at bytes 45-78 of the serialized xpub.
        // We assert that signer_pubkey() returns precisely Xpub::public_key
        // (the same field rust-bitcoin exposes), NOT a child-derived key.
        if let KeyField::Xpub { xpub, .. } = &r.key_field {
            assert_eq!(pk, xpub.public_key);
        } else {
            panic!("TV-2 must parse as KeyField::Xpub");
        }
    }
}
