//! Subcommand dispatch.

pub mod addresses;
pub mod build_descriptor;
pub mod bundle;
pub mod compare_cost;
pub mod convert;
pub mod decode_address;
pub mod derive_child;
pub mod electrum_decrypt;
pub mod export_wallet;
pub mod final_word;
pub mod gen_man;
pub mod gui_schema;
pub mod import_wallet;
pub mod inspect;
pub mod ms_shares;
pub mod nostr;
pub mod repair;
pub mod restore;
pub mod seed_xor;
pub mod seedqr;
pub mod silent_payment;
pub mod slip39;
pub mod verify_bundle;
pub mod verify_message;
pub mod word_card;
pub mod xpub_search;
