//! Public secret-class taxonomy.
//!
//! Source of truth for the `is_secret_bearing()` predicates on
//! `NodeType` (binary-private at `cmd/convert.rs`) and `SlotSubkey`
//! (binary-private at `slot_input.rs`), exposed for downstream tools
//! that cannot import the private enum modules.
//!
//! ## Why this module exists
//!
//! The `mnemonic-gui` repo's `persistence::redact_for_persistence`
//! filters slot rows + node-value composites against these two sets.
//! Prior to toolkit v0.14.0 / GUI v0.4.0, the GUI scraped the
//! toolkit's private source via `syn::parse_file` at GUI build time
//! to recover the same taxonomy — a fragile path whose stub-fallback
//! emitted `&[]` in cargo-install sandboxes, silently disabling
//! redaction and leaking BIP-39 phrases to `state.json`
//! (mnemonic-gui v0.3.0..v0.3.2; CVE-class bug; patched tactically in
//! v0.3.3, then retired structurally by this module).
//!
//! Architect-vetted Option A from the
//! `secret-taxonomy-public-api-promotion` FOLLOWUP entry:
//! `mnemonic-gui` (v0.4.0+) depends on `mnemonic-toolkit` as a
//! regular crate and `use mnemonic_toolkit::secret_taxonomy::*`.
//! Compile-time guarantee — empty SECRET_* arrays cannot ship.
//!
//! ## Single-source-of-truth invariant
//!
//! Per-variant parity tests in `cmd::convert::secret_taxonomy_parity_tests`
//! (against `NodeType::is_secret_bearing`) and `slot_input::tests`
//! (against `SlotSubkey::is_secret_bearing`) walk every enum variant
//! and assert `V.is_secret_bearing() == SECRET_*.contains(&V.as_str())`.
//!
//! The iteration source-of-truth is generated by a per-module
//! `declare_*_variants!` macro that takes a list of variant idents
//! and expands to BOTH (a) a `const ALL_*_VARIANTS: &[<Enum>]` array
//! used by the parity tests AND (b) a `fn _exhaustiveness_check`
//! whose `match v { Variant1 | Variant2 | ... => () }` body has no
//! wildcard. The two outputs share a single input list, so they
//! cannot diverge.
//!
//! Net guarantee: a future contributor who adds a new variant to
//! `NodeType` / `SlotSubkey`:
//!   1. Makes `_exhaustiveness_check`'s match non-exhaustive →
//!      **compile error** until they extend the macro input.
//!   2. Extending the macro input automatically adds the new variant
//!      to `ALL_*_VARIANTS` (same input expands to both outputs).
//!   3. The parity test then iterates the extended array. If the new
//!      variant's `is_secret_bearing()` is `true` but its `as_str()`
//!      is not in `SECRET_NODE_TYPES` / `SECRET_SLOT_SUBKEYS`, the
//!      parity assertion fires at test time.
//!
//! Net effect: a secret-bearing variant cannot land without being
//! mirrored into the relevant array below.
//!
//! ## Stability contract
//!
//! These slices are `pub const &[&str]`. Renaming, reordering, or
//! removing entries is a semver-minor event (pre-1.0 minor-axis
//! bump). New entries are additive and minor-safe.
//!
//! Re-exported by `lib.rs`. Module path:
//! `mnemonic_toolkit::secret_taxonomy::{SECRET_NODE_TYPES, SECRET_SLOT_SUBKEYS}`.

/// Token-form strings of every `NodeType` variant whose
/// `is_secret_bearing()` returns `true`. Mirrors
/// `cmd::convert::NodeType::is_secret_bearing` at
/// `crates/mnemonic-toolkit/src/cmd/convert.rs`.
///
/// **Excludes** `MiniKey` (Casascius mini-key): the toolkit's wider
/// `is_argv_secret_bearing()` predicate adds MiniKey, but that
/// distinction is intentional — see SPEC_secret_memory_hygiene §1 and
/// the `convert-minikey-stdout-redaction` FOLLOWUP. Persistence
/// redaction uses the narrower `is_secret_bearing()` set; downstream
/// argv-leakage tooling should track the wider set via a separate
/// constant when it lands.
pub const SECRET_NODE_TYPES: &[&str] = &[
    "phrase",
    "entropy",
    "xprv",
    "wif",
    "ms1",
    "bip38",
    "electrum-phrase",
];

/// Token-form strings of every `SlotSubkey` variant whose
/// `is_secret_bearing()` returns `true`. Mirrors
/// `slot_input::SlotSubkey::is_secret_bearing` at
/// `crates/mnemonic-toolkit/src/slot_input.rs`.
pub const SECRET_SLOT_SUBKEYS: &[&str] = &["phrase", "seedqr", "entropy", "xprv", "wif"];
